name: beware_travel_safe
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  google_maps_flutter: ^0.5.21+8
  geolocator: ^5.1.5
  provider: ^3.0.0
  intl: ^0.15.8
  http: ^0.12.0+2
  shared_preferences: ^0.5.3+1
 

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  fonts:
    - family: Product Sans
      fonts:
        - asset: assets/fonts/ProductSansBold.ttf
          weight: 600
        - asset: assets/fonts/ProductSansRegular.ttf
          weight: 400

  assets:
    - assets/images/introimage.png
    - assets/images/introbg.png
    - assets/images/authimage.png
    - assets/images/searchimage.png
    - assets/images/registerimage.png
    - assets/images/accidentselected.png
    - assets/images/accidentunselected.png
    - assets/images/crimeselected.png
    - assets/images/crimeunselected.png

  uses-material-design: true

